using MediatR;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Nestly.Application;
using Nestly.Application.Bookings;
using Nestly.Application.ProviderManagement;
using Nestly.Application.RecurringBookings;
using Nestly.Domain;
using Nestly.Domain.Events;
using Nestly.Infrastructure.Options;
using Nestly.Infrastructure.Persistence.Interceptors;

namespace Nestly.Infrastructure.Services;

/// <summary>
/// Tasks 246/247/248: automatic provider assignment, including the
/// rejection-retry chain and the <see cref="AutoAssignmentOptions.Enabled"/>
/// kill switch (PROVIDER.md OPEN DECISIONS - AUTOMATIC ASSIGNMENT). A fourth
/// independent handler on
/// <see cref="BookingStatusChangedEvent"/>, same shape as
/// <see cref="BookingNotificationTriggerHandler"/>/<see cref="ReferralQualifyingBookingHandler"/>
/// - reacts on its own rather than any of them knowing about the others.
///
/// Fires on every transition to <see cref="BookingStatus.AwaitingFulfilment"/>
/// (decision 4: after payment, not <see cref="BookingStatus.PaymentPending"/>
/// - task 240 established a PaymentPending booking may never be paid for at
/// all) - which covers both a fresh booking (task 246) and a rejection
/// (task 247) identically, since <c>BookingProviderAssignmentService.RejectInternalAsync</c>
/// already re-raises this same event when it returns a booking to
/// AwaitingFulfilment. No new coupling between that service and this handler
/// was needed for the retry chain - the existing event wiring already
/// delivers it; this handler only had to start reading the booking's own
/// assignment history to know it is a retry rather than a first attempt.
///
/// Ranks candidates via <see cref="IProviderMatchingService"/> (task 244, by
/// real road travel time since task 267),
/// excluding every provider with a Rejected or Expired row against this
/// booking (regardless of who assigned them - a rejection means "this
/// provider said no to this booking," and an expiry means they never
/// answered at all; both, full stop). Stops after
/// <see cref="AutoAssignmentOptions.RetryAttempts"/> system-attributed
/// rejections/expiries and leaves the booking for the manual queue rather
/// than retrying forever (decision 6). Walks the ranked list applying
/// <see cref="IProviderAssignmentEligibilityService"/> (task 245), and
/// assigns the first eligible one via
/// <see cref="IBookingProviderAssignmentService.AssignBySystemAsync"/>. No
/// eligible candidate is not an error (decision 5): the booking simply stays
/// AwaitingFulfilment, exactly where it already sits today for today's
/// unchanged manual admin queue to pick up.
///
/// Task 297 adds one preference and changes nothing else: when the booking
/// was generated by a recurring plan (task 296's
/// <see cref="Booking.RecurringBookingPlanId"/>), the plan's standing
/// provider - see <see cref="IRecurringPlanProviderContinuityService"/> - is
/// tried ahead of the ranked list, because a customer on a standing schedule
/// wants the same professional back rather than whoever happens to be
/// nearest this week. They face the identical eligibility gate as any other
/// candidate, and when they fail it the handler falls straight through to
/// the ranked walk below - the existing reassignment flow - so an
/// unavailable regular becomes a substitute, never a gap. Because
/// <see cref="IBookingProviderAssignmentService.AssignBySystemAsync"/>
/// supersedes whatever assignment is live via
/// <c>BookingProviderAssignment.MarkReassigned</c>, that substitution raises
/// <c>BookingProviderChangedEvent</c> and the customer is told their
/// professional changed (task 295).
///
/// A reschedule is the other time the job is offered back to someone already on it. <c>Booking.Reschedule</c> lands the
/// booking on AwaitingFulfilment again while the professional it was assigned to is still set, and without a preference
/// the ranked walk would hand the job to whoever is nearest - silently replacing a professional the customer was
/// already expecting (and the one replaced is told nothing). So on that hop (<c>FromStatus == Rescheduled</c>) the
/// professional already on the job is tried first, under the same eligibility gate as every other candidate: they keep
/// the job when the new time works for them and are replaced by the ranked walk only when it does not. They are
/// re-offered the job (a fresh assignment row, so they confirm the new time) rather than having their old row carried
/// over, which is how every other assignment of a booking already works.
/// </summary>
public sealed class ProviderAutoAssignmentHandler : INotificationHandler<DomainEventNotification<BookingStatusChangedEvent>>
{
    private readonly IEligibleProviderSearchService _eligibleProviderSearch;
    private readonly IProviderAssignmentEligibilityService _eligibilityService;
    private readonly IBookingProviderAssignmentService _assignmentService;
    private readonly IBookingProviderAssignmentRepository _assignmentRepository;
    private readonly IBookingRepository _bookingRepository;
    private readonly IRecurringPlanProviderContinuityService _continuityService;
    private readonly IOptions<AutoAssignmentOptions> _options;
    private readonly ILogger<ProviderAutoAssignmentHandler> _logger;

    public ProviderAutoAssignmentHandler(
        IEligibleProviderSearchService eligibleProviderSearch,
        IProviderAssignmentEligibilityService eligibilityService,
        IBookingProviderAssignmentService assignmentService,
        IBookingProviderAssignmentRepository assignmentRepository,
        IBookingRepository bookingRepository,
        IRecurringPlanProviderContinuityService continuityService,
        IOptions<AutoAssignmentOptions> options,
        ILogger<ProviderAutoAssignmentHandler> logger)
    {
        _eligibleProviderSearch = eligibleProviderSearch;
        _eligibilityService = eligibilityService;
        _assignmentService = assignmentService;
        _assignmentRepository = assignmentRepository;
        _bookingRepository = bookingRepository;
        _continuityService = continuityService;
        _options = options;
        _logger = logger;
    }

    public async Task Handle(DomainEventNotification<BookingStatusChangedEvent> notification, CancellationToken cancellationToken)
    {
        var domainEvent = notification.DomainEvent;
        if (domainEvent.ToStatus != BookingStatus.AwaitingFulfilment)
        {
            return;
        }

        if (!_options.Value.Enabled)
        {
            // Task 248's kill switch - no logging noise on the (expected to
            // be common) disabled path; ProviderAutoAssignmentHandlerTests
            // covers this branch, and a genuinely surprising "why didn't
            // this booking get auto-assigned" investigation starts from the
            // config, not a log line for every single booking.
            return;
        }

        // Row 81, docs/OPEN-FIXES-FEATURES.csv: DomainEventDispatchInterceptor
        // publishes this notification as soon as the SaveChangesAsync that
        // raised it completes, which - despite that interceptor's own doc
        // comment - is not the same moment as "the transaction that raised
        // it has committed" when the caller is itself running inside an
        // explicit, still-open BeginTransactionAsync (as
        // BookingProviderAssignmentService.AssignInternalAsync's manual-
        // admin-on-a-Confirmed-booking path is: it walks Confirmed ->
        // AwaitingFulfilment -> Assigned in one call, and both transitions'
        // events are dispatched together the moment its own UpdateAsync
        // saves, before its own dbTransaction.CommitAsync() is ever reached).
        // Without this guard, this handler would react to the intermediate
        // AwaitingFulfilment hop and call AssignBySystemAsync, which tries to
        // open a second Serializable transaction on that same still-open
        // connection - forbidden, and surfaced to the admin as a generic 500
        // rather than the DbUpdateException catch further down the call
        // chain is written to expect. Re-reading the booking's live status
        // (the same tracked instance the caller already mutated, thanks to
        // EF's identity map - no second round trip) is what tells this
        // handler someone already moved the booking on within this same unit
        // of work, so there is nothing left for auto-assignment to do.
        var currentBooking = await _bookingRepository.GetByIdAsync(domainEvent.BookingId);
        if (currentBooking is null || currentBooking.Status != BookingStatus.AwaitingFulfilment)
        {
            return;
        }

        var history = await _assignmentRepository.ListByBookingAsync(domainEvent.BookingId);

        // Expired counts the same as Rejected here (task: assignment-response
        // expiry) - a provider who never answered gets exactly one attempt at
        // this booking too, same as one who explicitly declined it.
        int systemNonResponses = history.Count(a =>
            a.AssignedByType == BookingAssignedByType.System
            && a.Status is BookingProviderAssignmentStatus.Rejected or BookingProviderAssignmentStatus.Expired);
        if (systemNonResponses >= _options.Value.RetryAttempts)
        {
            _logger.LogInformation(
                "Booking {BookingId} hit the auto-assignment retry cap ({RetryAttempts}); leaving for manual admin assignment.",
                domainEvent.BookingId, _options.Value.RetryAttempts);
            return;
        }

        var excludeProviderIds = history
            .Where(a => a.Status is BookingProviderAssignmentStatus.Rejected or BookingProviderAssignmentStatus.Expired)
            .Select(a => a.ProviderId)
            .ToList();

        // Only the reschedule hop: every other way back to AwaitingFulfilment (a rejection, an expiry, an admin
        // unassigning) has already cleared the professional, so there is nobody to prefer.
        Guid? professionalOnTheJob = domainEvent.FromStatus == BookingStatus.Rescheduled ? currentBooking.AssignedProviderId : null;

        await TryAssignAsync(domainEvent.BookingId, excludeProviderIds, cancellationToken, professionalOnTheJob);
    }

    /// <summary>
    /// Assigns the first eligible ranked candidate not in <paramref name="excludeProviderIds"/>, after first offering the
    /// job back to <paramref name="currentProviderId"/> - the professional already on a booking that is only being moved
    /// (a reschedule) - and then to a recurring plan's standing provider (task 297). Returns whether a provider was
    /// assigned, so callers can tell an eligible pick from "nothing left to try."
    /// </summary>
    public async Task<bool> TryAssignAsync(
        Guid bookingId, IReadOnlyCollection<Guid>? excludeProviderIds, CancellationToken cancellationToken = default, Guid? currentProviderId = null)
    {
        if (currentProviderId is { } current)
        {
            // Not subject to excludeProviderIds: they hold the live assignment right now, so whatever they once did on
            // this booking (an earlier rejection, say, before an admin put them back on it) has been overtaken.
            if (await _eligibilityService.IsEligibleAsync(current, bookingId, cancellationToken)
                && await TryAssignStandingProviderAsync(bookingId, current, "the professional already on the rescheduled booking"))
            {
                return true;
            }

            excludeProviderIds = [.. excludeProviderIds ?? [], current];
        }

        var standingProviderId = await FindStandingProviderAsync(bookingId, excludeProviderIds, cancellationToken);
        if (standingProviderId is not null && await TryAssignStandingProviderAsync(bookingId, standingProviderId.Value, "its recurring plan's standing provider"))
        {
            return true;
        }

        // The standing provider has already had its turn and failed, so drop
        // it before the ranked walk re-derives the same answer. Stated
        // honestly: this changes cost, not outcome - the matcher already
        // filters non-Active providers and the walk re-applies the identical
        // eligibility gate, so removing this line leaves every current
        // behaviour intact. It earns its place by saving one redundant
        // IsEligibleAsync, which can be a billed route lookup (task 289), and
        // by saying out loud that the fall-through is a *reassignment* rather
        // than a retry of the same unavailable person.
        var excluded = standingProviderId is { } standing
            ? [.. excludeProviderIds ?? [], standing]
            : excludeProviderIds;

        await foreach (var candidate in _eligibleProviderSearch.FindEligibleAsync(bookingId, excluded, cancellationToken))
        {
            var result = await _assignmentService.AssignBySystemAsync(bookingId, candidate.ProviderId);
            if (result.IsSuccess)
            {
                // Both figures, because they answer different questions: the
                // km is straight-line (unchanged units, task 243), while the
                // travel time is what actually ordered the list (task 267) -
                // and is null when the ranking fell back to distance.
                _logger.LogInformation(
                    "Auto-assigned provider {ProviderId} to booking {BookingId} ({DistanceKm} km straight line, {TravelDurationSeconds} s by road).",
                    candidate.ProviderId, bookingId, candidate.DistanceKm, candidate.TravelDurationSeconds);
                return true;
            }

            // Lost a race (e.g. the provider was suspended or the booking
            // moved on between the eligibility check and the assign call) -
            // try the next candidate rather than giving up on the whole
            // booking over one contended pick.
            _logger.LogWarning(
                "Auto-assignment of provider {ProviderId} to booking {BookingId} failed ({ErrorCode}); trying the next candidate.",
                candidate.ProviderId, bookingId, result.Error.Code);
        }

        _logger.LogInformation("No eligible provider found to auto-assign booking {BookingId}; left for manual admin assignment.", bookingId);
        return false;
    }

    /// <summary>
    /// Task 297. The provider a recurring plan's customer already knows, or
    /// null when this booking is a one-off, the plan has no history yet, or
    /// that provider is on the caller's exclusion list (they rejected this
    /// very booking - continuity does not survive a "no").
    /// </summary>
    private async Task<Guid?> FindStandingProviderAsync(
        Guid bookingId, IReadOnlyCollection<Guid>? excludeProviderIds, CancellationToken cancellationToken)
    {
        var booking = await _bookingRepository.GetByIdAsync(bookingId);
        if (booking?.RecurringBookingPlanId is not { } planId)
        {
            return null;
        }

        var standingProviderId = await _continuityService.FindStandingProviderAsync(planId, bookingId);
        if (standingProviderId is null || excludeProviderIds?.Contains(standingProviderId.Value) == true)
        {
            return null;
        }

        // Same gate every ranked candidate faces (task 245), applied here
        // rather than being assumed away: continuity is a preference in the
        // ordering, never an exemption from availability, capacity,
        // double-booking or travel feasibility.
        return await _eligibilityService.IsEligibleAsync(standingProviderId.Value, bookingId, cancellationToken)
            ? standingProviderId
            : null;
    }

    private async Task<bool> TryAssignStandingProviderAsync(Guid bookingId, Guid standingProviderId, string who)
    {
        var result = await _assignmentService.AssignBySystemAsync(bookingId, standingProviderId);
        if (result.IsSuccess)
        {
            _logger.LogInformation(
                "Auto-assigned booking {BookingId} back to {Who} {ProviderId}.",
                bookingId, who, standingProviderId);
            return true;
        }

        _logger.LogWarning(
            "Could not keep {Who} {ProviderId} on booking {BookingId} ({ErrorCode}); falling back to reassignment.",
            who, standingProviderId, bookingId, result.Error.Code);
        return false;
    }
}
