using Nestly.Application.Bookings;
using Nestly.Domain;

namespace Nestly.Application.ProviderJobs;

/// <summary>
/// The provider-facing view of a job's status (task 149a, PROVIDER.md API
/// surface "Jobs"). Not a persisted enum - derived at read time from the
/// combination of <see cref="BookingProviderAssignment.Status"/> (the offer/
/// response) and <see cref="Booking.Status"/> (execution progress), since
/// PROVIDER.md's SCOPE BOUNDARY keeps those two concepts in separate
/// entities. See <c>ProviderJobService.ToJobStatus</c> for the mapping.
/// </summary>
public enum ProviderJobStatus
{
    /// <summary>Offered to the provider; awaiting accept/reject.</summary>
    Assigned,

    /// <summary>Accepted, not yet started (booking still Assigned).</summary>
    Accepted,

    /// <summary>The provider declined this offer.</summary>
    Rejected,

    /// <summary>Superseded by a later (re)assignment before this provider responded.</summary>
    Reassigned,

    /// <summary>Accepted and the provider has started work (booking InProgress).</summary>
    InProgress,

    /// <summary>Work finished (booking Completed).</summary>
    Completed,

    /// <summary>The booking was cancelled (by the customer or an admin) while this assignment was still outstanding or accepted - nothing left for the provider to do (task 208).</summary>
    Withdrawn,

    // Task 270: the provider-facing projection of task 264's two fulfilment
    // states, so /en-route and /arrived answer with a status the caller can
    // tell apart from Accepted. Appended rather than slotted in after
    // Accepted where they belong chronologically: provider-api registers no
    // JsonStringEnumConverter, so this enum crosses the wire as its ordinal
    // and frontend/provider-web/src/lib/jobs-types.ts mirrors those ordinals
    // by hand - inserting mid-enum would renumber InProgress onwards and
    // silently remap every already-deployed client's job status.

    /// <summary>Accepted and the provider is travelling to the address (booking <see cref="Nestly.Domain.BookingStatus.ProviderEnRoute"/>).</summary>
    EnRoute,

    /// <summary>Accepted and the provider has reached the address but has not begun work (booking <see cref="Nestly.Domain.BookingStatus.ProviderArrived"/>).</summary>
    Arrived
}

public sealed record ProviderJobItemResponse(string NameSnapshot, int Quantity, decimal UnitPriceSnapshot);

/// <summary>
/// One row in the provider's job list (task 149a "list jobs").
///
/// <see cref="RecurringBookingPlanId"/>/<see cref="RecurringFrequency"/> are
/// task 300: a job generated by a <see cref="RecurringBookingPlan"/> is one
/// visit in a standing customer relationship rather than a one-off, and a
/// provider who cannot tell the two apart cannot plan around it. Both are null
/// for an ordinary booking, and both are read live through
/// <see cref="Booking.RecurringBookingPlanId"/> (task 296's FK) rather than
/// snapshotted onto the booking - see
/// <c>IRecurringBookingPlanRepository.ListFrequenciesByIdsAsync</c>.
///
/// Only the cadence is exposed, not the plan's whole schedule: the provider's
/// standing relationship is with the customer, and how many visits remain on
/// the customer's plan (or when it ends) is the customer's business, not
/// something the assignment entitles this provider to know.
/// </summary>
public sealed record ProviderJobSummaryResponse(
    Guid AssignmentId,
    Guid BookingId,
    ProviderJobStatus Status,
    string CustomerNameSnapshot,
    string CustomerMobileSnapshot,
    string AddressLine1Snapshot,
    string AddressCitySnapshot,
    string AddressPincodeSnapshot,
    DateOnly SlotDate,
    TimeSpan SlotStartTimeSnapshot,
    TimeSpan SlotEndTimeSnapshot,
    // The customer's gross booking total (service value + tax + platform
    // fee) - NOT the provider's earning. See CommissionAmount/
    // NetAmountToProvider below for the actual payout breakdown (bug fix:
    // provider-web was previously showing this figure as "you'll earn").
    decimal TotalPayableSnapshot,
    DateTime AssignedAt,
    DateTime? ResponseDeadline,
    Guid? RecurringBookingPlanId,
    RecurringBookingRecurrenceFrequency? RecurringFrequency,
    // Short human-facing code ("GLX-260825-K7F3M") - see Booking.BookingReference's
    // doc comment.
    string BookingReference,
    // Payout breakdown (bug fix, docs/OPEN-FIXES-FEATURES.csv "Payout
    // figure"): the platform commission (task 157's ICommissionService,
    // same rate/amount the escrow settlement in EscrowReleaseOnCompletionHandler
    // actually deducts) and what is left for the provider once it is.
    // Appended last: this is a positional record.
    decimal CommissionAmount,
    decimal NetAmountToProvider);

public sealed record ProviderJobSearchResponse(IReadOnlyList<ProviderJobSummaryResponse> Items);

/// <summary>One job's full detail (task 149a "get job detail").</summary>
public sealed record ProviderJobDetailResponse(
    Guid AssignmentId,
    Guid BookingId,
    ProviderJobStatus Status,
    string CustomerNameSnapshot,
    string CustomerMobileSnapshot,
    string AddressLabelSnapshot,
    string AddressLine1Snapshot,
    string? AddressLine2Snapshot,
    string? AddressLandmarkSnapshot,
    string AddressCitySnapshot,
    string AddressStateSnapshot,
    string AddressPincodeSnapshot,
    string AddressContactNameSnapshot,
    string AddressContactMobileSnapshot,
    DateOnly SlotDate,
    TimeSpan SlotStartTimeSnapshot,
    TimeSpan SlotEndTimeSnapshot,
    IReadOnlyList<ProviderJobItemResponse> Items,
    // The customer's gross booking total (service value + tax + platform
    // fee) - NOT the provider's earning. See CommissionAmount/
    // NetAmountToProvider below for the actual payout breakdown (bug fix:
    // provider-web was previously showing this figure as "you'll earn").
    decimal TotalPayableSnapshot,
    DateTime AssignedAt,
    DateTime? RespondedAt,
    DateTime? ResponseDeadline,
    string? Notes,
    string? CompletionProofRef,
    // Short human-facing code ("GLX-260825-K7F3M") - see Booking.BookingReference's
    // doc comment.
    string BookingReference,
    // Payout breakdown (bug fix, docs/OPEN-FIXES-FEATURES.csv "Payout
    // figure"): the platform commission (task 157's ICommissionService, same
    // rate/amount the escrow settlement in EscrowReleaseOnCompletionHandler
    // actually deducts) and what is left for the provider once it is.
    // Appended last: this is a positional record.
    decimal CommissionAmount,
    decimal NetAmountToProvider);

/// <summary>Provider rejects an offered job (task 149a "reject job"), same shape as the admin-facing <c>RejectAssignmentRequest</c>.</summary>
public sealed record RejectJobRequest(string? Reason);

/// <summary>Attach completion evidence to an accepted job (task 149a "upload completion proof"). <c>ProofRef</c> is a reference to an already-uploaded file (storage key/URL), matching how KYC documents are submitted.</summary>
public sealed record UploadJobCompletionProofRequest(string ProofRef);

/// <summary>
/// A camera/gallery photo the provider captured on-site for completion
/// verification, just uploaded and now servable at <see cref="PhotoRef"/> -
/// the client feeds this ref straight into <see cref="Nestly.Application.Bookings.SubmitCompletionProofRequest.PhotoRefs"/>,
/// the same reference-only convention every other photo/document field in
/// this codebase already uses.
/// </summary>
public sealed record UploadCompletionPhotoResponse(string PhotoRef);
