using Nestly.Domain;

namespace Nestly.Application.Bookings;

public interface IBookingRepository
{
    Task AddAsync(Booking booking);

    /// <summary>Task 241: same TryAdd-under-a-unique-index shape as IPaymentTransactionRepository.TryAddAsync - returns false if IdempotencyKey lost the race against a concurrent duplicate request rather than throwing. Only meaningful when booking.IdempotencyKey is non-null; BookingConfiguration's unique index never rejects two null keys.</summary>
    Task<bool> TryAddAsync(Booking booking);

    /// <summary>Task 241: the other half of the idempotency check - null if no booking (for this customer) was created from this key yet.</summary>
    Task<Booking?> GetByIdempotencyKeyAsync(Guid customerId, string idempotencyKey);

    Task UpdateAsync(Booking booking);

    /// <summary>
    /// Task 333: throws away <paramref name="booking"/>'s unsaved changes and
    /// stops tracking it, so a caller that mutated an aggregate and then failed
    /// to persist it can leave the unit of work exactly as it found it.
    ///
    /// <para>
    /// This exists because a persistence context batches: one unit of work
    /// holds every aggregate loaded through it, and saving <i>any</i> of them
    /// flushes the pending changes of <i>all</i> of them. Without this, a
    /// booking whose own save threw would still be written by the next
    /// booking's successful save - so a batch job's "this one failed, carry
    /// on" would silently commit the very change it just reported as failed,
    /// and whether it did would depend on the order rows came back in.
    /// </para>
    ///
    /// <para>
    /// Only ever correct on an aggregate whose changes are <b>meant</b> to be
    /// abandoned; it is not a rollback of anything already written.
    /// </para>
    /// </summary>
    void DiscardChanges(Booking booking);

    /// <summary>Loaded with its items, their add-ons, and its status history - a booking is never useful partially loaded.</summary>
    Task<Booking?> GetByIdAsync(Guid id);

    /// <summary><paramref name="statuses"/> is the expansion of a <see cref="BookingStatusBucket"/> via <see cref="BookingStatusMapper.StatusesInBucket"/>.</summary>
    Task<IReadOnlyList<Booking>> ListByCustomerAsync(Guid customerId, IReadOnlyList<BookingStatus> statuses);

    /// <summary>
    /// Paged counterpart to <see cref="ListByCustomerAsync"/>, newest first, for
    /// the customer's own "My bookings" list (SRS 11.13, task 60b). A separate
    /// method rather than an optional parameter on the unpaged one: the two
    /// other callers of <see cref="ListByCustomerAsync"/> (Nestly Coins'
    /// eligibility check, the admin customer-360 profile) both genuinely need
    /// every booking, not a page of them, and must not silently start missing
    /// rows if this gains a default page size later.
    /// </summary>
    Task<(IReadOnlyList<Booking> Rows, int TotalCount)> ListByCustomerPagedAsync(Guid customerId, IReadOnlyList<BookingStatus> statuses, int page, int pageSize);

    /// <summary>Filterable, paginated admin search across every booking (SRS 12.11.1, task 115a).</summary>
    Task<BookingSearchResult> SearchAsync(BookingSearchFilter filter);

    /// <summary>Bookings currently assigned to a provider (<see cref="Booking.AssignedProviderId"/>), for the admin performance view (task 150c). Reflects the live assignment only - a booking whose assignment was later rejected/reassigned away from this provider will no longer appear here, even though <c>BookingProviderAssignment</c> retains that history.</summary>
    Task<IReadOnlyList<Booking>> ListByAssignedProviderAsync(Guid providerId);

    /// <summary>
    /// Every booking generated by one recurring plan (task 296's
    /// <see cref="Booking.RecurringBookingPlanId"/>), newest slot date first -
    /// the read the customer's plan detail (task 298) and the admin plan view
    /// (task 299) both make. Deliberately reads the booking table by its own
    /// indexed FK column rather than joining through
    /// <c>recurring_booking_occurrence</c>: the occurrence log also holds
    /// skipped dates that never produced a booking, so a join through it would
    /// have to filter them back out, and the answer to "which bookings came
    /// from this plan" must not depend on the audit log still being intact.
    /// </summary>
    Task<IReadOnlyList<Booking>> ListByRecurringPlanAsync(Guid recurringBookingPlanId);

    /// <summary>Nestly Coins' reorder check (docs/NESTLY-COINS.md GUIDELINES #2, task 201): does this customer have any OTHER Completed booking besides <paramref name="excludingBookingId"/>? A dedicated count query, mirroring <c>IReferralRepository.CountRewardedByReferrerAsync</c>'s convention, rather than listing and filtering full booking rows client-side.</summary>
    Task<int> CountCompletedByCustomerAsync(Guid customerId, Guid excludingBookingId);

    /// <summary>Nestly Coins' reorder check, provider side (docs/NESTLY-COINS.md GUIDELINES #2, task 201): does this provider have any OTHER Completed booking besides <paramref name="excludingBookingId"/>?</summary>
    Task<int> CountCompletedByAssignedProviderAsync(Guid providerId, Guid excludingBookingId);

    /// <summary>Task 240: PaymentPending bookings created before <paramref name="olderThanUtc"/> - BookingExpirySweepJob's candidate set. Still PaymentPending only; one that already moved to Confirmed/PaymentFailed/CancelledByCustomer never matches regardless of age.</summary>
    Task<IReadOnlyList<Booking>> ListStalePaymentPendingAsync(DateTime olderThanUtc);

    /// <summary>
    /// Task 333: <see cref="BookingStatus.Confirmed"/> bookings whose slot
    /// falls between <paramref name="onOrAfterSlotDate"/> and
    /// <paramref name="onOrBeforeSlotDate"/> inclusive -
    /// <c>BookingFulfilmentPromotionJob</c>'s candidate set, ordered by slot
    /// date so the most urgent come first, and windowed by
    /// <paramref name="skip"/>/<paramref name="take"/> so a backlog is paged
    /// rather than loaded whole.
    ///
    /// <para>
    /// Both dates are <b>business-local</b>, not UTC, because
    /// <see cref="Booking.SlotDate"/> is stored that way (see
    /// <c>IBusinessClock</c>); the caller converts once rather than this query
    /// doing timezone arithmetic per row. They are deliberately whole boundary
    /// <i>days</i> rather than exact instants: the caller owns the
    /// hour-precision half of both ends of the window, because
    /// <see cref="Booking.SlotStartTimeSnapshot"/> is a <c>TimeSpan</c> and
    /// ordering comparisons on it are not translatable on both of this
    /// project's database providers (they are on PostgreSQL's <c>interval</c>,
    /// not on the SQLite the test suite runs). Pushing the days down and
    /// applying the time of day in memory keeps one implementation of the rule
    /// that works everywhere, instead of raw SQL that has to be written twice.
    /// </para>
    ///
    /// <para>
    /// Task 358: <paramref name="onOrAfterSlotDate"/> is the lower bound this
    /// query originally lacked. A booking whose slot has already started while
    /// still <see cref="BookingStatus.Confirmed"/> is a candidate rather than
    /// being quietly left behind - it has nobody assigned and needs one more
    /// urgently than any future booking - but only while somebody can still
    /// realistically be sent. Without a floor, the first pass in any environment
    /// swept the whole history of past-dated Confirmed rows into the manual
    /// admin queue at once (see <c>AutoAssignmentOptions.PromotionMaxSlotAgeHours</c>).
    /// </para>
    /// </summary>
    Task<IReadOnlyList<Booking>> ListConfirmedDueForFulfilmentAsync(DateOnly onOrAfterSlotDate, DateOnly onOrBeforeSlotDate, int skip, int take);

    /// <summary>
    /// Task 255: bookings for a set of ids in one round trip, for list
    /// screens that resolve a booking per row. Read-only and deliberately
    /// NOT fully loaded - unlike <see cref="GetByIdAsync"/> it omits items,
    /// add-ons and status history, because the callers (the provider job
    /// list) read only the booking's snapshot columns and its status.
    /// Ids with no matching booking are simply absent from the result.
    /// </summary>
    Task<IReadOnlyList<Booking>> ListSummariesByIdsAsync(IReadOnlyCollection<Guid> ids);

    /// <summary>
    /// Distinct <see cref="BookingItem.ServiceId"/>s that appear in ANY
    /// booking ever placed, regardless of that booking's current status -
    /// docs/OPEN-FIXES-FEATURES.csv "Admin Web, Proposed new page, Catalog
    /// health"'s "never booked" check. A service absent from this set has no
    /// booking history at all, launched or not.
    /// </summary>
    Task<IReadOnlyList<Guid>> ListServiceIdsEverBookedAsync();

    /// <summary>
    /// Row "Unassigned and at-risk queue", docs/OPEN-FIXES-FEATURES.csv: paid
    /// bookings a live assignment could still be pushed onto -
    /// <see cref="BookingStatus.Confirmed"/>, <see cref="BookingStatus.AwaitingFulfilment"/>
    /// or <see cref="BookingStatus.Assigned"/>, the same admin allow-list
    /// <c>BookingProviderAssignmentService.IsAssignableStatus</c> uses - that
    /// currently have no live provider (<see cref="Booking.AssignedProviderId"/>
    /// is null). Assigned is included only for symmetry with that gate: in
    /// practice a booking is never Assigned with a null AssignedProviderId,
    /// since <see cref="Booking.AssignProvider"/> is what puts it in that
    /// status and always sets both together. Paged and sorted soonest slot
    /// first (<see cref="Booking.SlotDate"/>/<see cref="Booking.SlotStartTimeSnapshot"/>
    /// ascending, tie-broken on <see cref="Booking.Id"/> for a stable total
    /// order across pages) so the most at-risk booking surfaces first.
    /// </summary>
    Task<(IReadOnlyList<Booking> Rows, int TotalCount)> ListUnassignedAtRiskAsync(int page, int pageSize);

    /// <summary>
    /// Every booking currently <see cref="BookingStatus.PaymentPending"/> or
    /// <see cref="BookingStatus.PaymentFailed"/> - "Awaiting Payment"/
    /// "Payment Failed" in <see cref="BookingStatusMapper"/>'s customer-facing
    /// labels, and the payment reconciliation view's candidate set
    /// (docs/OPEN-FIXES-FEATURES.csv "Payment reconciliation"). Cross-
    /// referenced there against <see cref="Nestly.Application.Payments.IPaymentTransactionRepository.ListByBookingIdsAsync"/>
    /// to classify each one as stuck-pending, failed or orphaned - a small,
    /// bounded operational list, same "not a candidate set that could ever
    /// need database-level paging" reasoning as <see cref="ListUnassignedAtRiskAsync"/>.
    /// </summary>
    Task<IReadOnlyList<Booking>> ListAwaitingPaymentAsync();
}
