/**
 * Response/request shapes for the Provider API's jobs surface (`/api/v1/jobs`,
 * docs/PROVIDER.md's `booking_provider_assignment` bridge table).
 *
 * Mirrors backend/shared/Application/ProviderJobs/ProviderJobContracts.cs
 * (ProviderJobSummaryResponse / ProviderJobSearchResponse / ProviderJobDetailResponse)
 * field-for-field, camelCased per ASP.NET Core's default JSON naming policy -
 * keep the two in sync if that file changes.
 */

/**
 * Mirrors Nestly.Application.ProviderJobs.ProviderJobStatus's declaration order
 * exactly. provider-api has no JsonStringEnumConverter registered, so this
 * enum serialises over the wire as its ordinal (a plain number), not its
 * name - same convention as customer-web's BookingStatus (lib/types.ts) -
 * keep this in sync with ProviderJobContracts.cs if that enum's order changes.
 */
export enum JobStatus {
  Assigned = 0,
  Accepted = 1,
  Rejected = 2,
  Reassigned = 3,
  InProgress = 4,
  Completed = 5,
  Withdrawn = 6,
  EnRoute = 7,
  Arrived = 8,
}

export const JOB_STATUS_LABELS: Record<JobStatus, string> = {
  [JobStatus.Assigned]: "Assigned",
  [JobStatus.Accepted]: "Accepted",
  [JobStatus.Rejected]: "Rejected",
  [JobStatus.Reassigned]: "Reassigned",
  [JobStatus.InProgress]: "In progress",
  [JobStatus.Completed]: "Completed",
  [JobStatus.Withdrawn]: "Cancelled by customer",
  [JobStatus.EnRoute]: "On the way",
  [JobStatus.Arrived]: "Arrived",
};

export function jobStatusLabel(status: JobStatus): string {
  return JOB_STATUS_LABELS[status] ?? String(status);
}

/**
 * Mirrors Nestly.Domain.RecurringBookingRecurrenceFrequency's declaration
 * order exactly. Same ordinal-over-the-wire convention as JobStatus above -
 * keep in sync with the C# enum if its order ever changes.
 */
export enum RecurrenceFrequency {
  Weekly = 0,
  Biweekly = 1,
  Monthly = 2,
}

export const RECURRENCE_FREQUENCY_LABELS: Record<RecurrenceFrequency, string> = {
  [RecurrenceFrequency.Weekly]: "Every week",
  [RecurrenceFrequency.Biweekly]: "Every 2 weeks",
  [RecurrenceFrequency.Monthly]: "Every month",
};

export function recurrenceFrequencyLabel(frequency: RecurrenceFrequency): string {
  return RECURRENCE_FREQUENCY_LABELS[frequency] ?? String(frequency);
}

/** One row in the provider's job list (GET /jobs). */
export interface JobListItem {
  assignmentId: string;
  bookingId: string;
  status: JobStatus;
  customerNameSnapshot: string;
  customerMobileSnapshot: string;
  addressLine1Snapshot: string;
  addressCitySnapshot: string;
  addressPincodeSnapshot: string;
  slotDate: string;
  slotStartTimeSnapshot: string;
  slotEndTimeSnapshot: string;
  /**
   * The customer's gross booking total (service value + tax + platform fee)
   * - NOT the provider's earning. Render `netAmountToProvider` for that; see
   * its doc comment for why (docs/OPEN-FIXES-FEATURES.csv "Payout figure").
   */
  totalPayableSnapshot: number;
  assignedAt: string;
  responseDeadline: string | null;
  /**
   * Set when this job was generated by a customer's recurring plan (task 300)
   * rather than booked one-off; null otherwise. The plan id is not linkable
   * from provider-web - a provider has no plan screen - but it identifies
   * which standing relationship a job belongs to when several are in flight.
   */
  recurringBookingPlanId: string | null;
  /** The plan's cadence, read live from the plan rather than snapshotted onto the booking. Null exactly when `recurringBookingPlanId` is. */
  recurringFrequency: RecurrenceFrequency | null;
  /** Short human-facing code ("GLX-260825-K7F3M") - what to show instead of `bookingId`. */
  bookingReference: string;
  /** Platform commission deducted from `totalPayableSnapshot` before it reaches the provider (backend's ICommissionService, task 157). */
  commissionAmount: number;
  /** What the provider actually earns on this job: `totalPayableSnapshot - commissionAmount`. This is the figure to show as "you'll earn" - never `totalPayableSnapshot`. */
  netAmountToProvider: number;
}

/** GET /jobs's actual response envelope (ProviderJobSearchResponse). */
export interface JobListResponse {
  items: JobListItem[];
}

/** Query parameters for GET /jobs. Both optional. */
export interface JobListParams {
  status?: string;
  date?: string;
}

export interface JobLineItem {
  nameSnapshot: string;
  quantity: number;
  unitPriceSnapshot: number;
}

/** Detail view of a single assignment (GET /jobs/{bookingId}). */
export interface JobDetail {
  assignmentId: string;
  bookingId: string;
  status: JobStatus;
  customerNameSnapshot: string;
  customerMobileSnapshot: string;
  addressLabelSnapshot: string;
  addressLine1Snapshot: string;
  addressLine2Snapshot: string | null;
  addressLandmarkSnapshot: string | null;
  addressCitySnapshot: string;
  addressStateSnapshot: string;
  addressPincodeSnapshot: string;
  addressContactNameSnapshot: string;
  addressContactMobileSnapshot: string;
  slotDate: string;
  slotStartTimeSnapshot: string;
  slotEndTimeSnapshot: string;
  items: JobLineItem[];
  /**
   * The customer's gross booking total (service value + tax + platform fee)
   * - NOT the provider's earning. Render `netAmountToProvider` for that; see
   * its doc comment for why (docs/OPEN-FIXES-FEATURES.csv "Payout figure").
   */
  totalPayableSnapshot: number;
  assignedAt: string;
  respondedAt: string | null;
  responseDeadline: string | null;
  notes: string | null;
  completionProofRef: string | null;
  /** Short human-facing code ("GLX-260825-K7F3M") - what to show instead of `bookingId`. */
  bookingReference: string;
  /** Platform commission deducted from `totalPayableSnapshot` before it reaches the provider (backend's ICommissionService, task 157). */
  commissionAmount: number;
  /** What the provider actually earns on this job: `totalPayableSnapshot - commissionAmount`. This is the figure to show as "you'll earn" - never `totalPayableSnapshot`. */
  netAmountToProvider: number;
}

export interface SubmitCompletionProofRequest {
  proofRef: string;
}

/**
 * Completion verification shapes mirror the C# records in
 * Nestly.Application.Bookings (BookingCompletionProofContracts.cs) - tasks
 * 195-197. Distinct from SubmitCompletionProofRequest's single legacy
 * proof-ref field above: this is the richer photos+checklist evidence that
 * gates the InProgress -> Completed transition (task 196).
 */

export interface CompletionChecklistAnswer {
  item: string;
  completed: boolean;
  notes: string | null;
}

export interface SubmitCompletionVerificationRequest {
  photoRefs: string[];
  checklistAnswers: CompletionChecklistAnswer[];
}

export interface BookingCompletionProofResponse {
  id: string;
  bookingId: string;
  photoRefs: string[];
  checklistAnswers: CompletionChecklistAnswer[];
  submittedByProviderId: string;
  submittedAtUtc: string;
}

/** Mirrors Nestly.Application.ProviderJobs.UploadCompletionPhotoResponse - the just-uploaded photo's ref, already an absolute URL. */
export interface UploadCompletionPhotoResponse {
  photoRef: string;
}

/**
 * Mirrors Nestly.Application.ProviderJobs.RecordProviderLocationRequest/
 * Response (ProviderLocationContracts.cs) - task 282's client for task 269's
 * ingest endpoint. `accuracyMetres` is optional on the wire (nullable on the
 * C# side) since not every browser/device reports one.
 */
export interface RecordProviderLocationRequest {
  latitude: number;
  longitude: number;
  accuracyMetres: number | null;
  recordedAtUtc: string;
}

export interface RecordProviderLocationResponse {
  accepted: boolean;
  pingId: string | null;
  nextAcceptedAfterUtc: string;
}

/**
 * Bidirectional reviews - the provider's private rating of the customer.
 * Mirrors Nestly.Application.CustomerRatings.CustomerRatingContracts.cs.
 * Never shown to the customer (admin-only, on the Customer 360 view).
 */
export interface CustomerRatingEligibility {
  isEligible: boolean;
  ineligibilityReason: string | null;
}

export interface SubmitCustomerRatingRequest {
  rating: number;
  note: string | null;
}

export interface CustomerRatingResponse {
  id: string;
  bookingId: string;
  customerId: string;
  rating: number;
  note: string | null;
  createdAtUtc: string;
}
